// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quorum.Persistence;

#nullable disable

namespace Quorum.Persistence.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815094537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quorum.Domain.Entities.AdminLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Values")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin_Logs", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.CloudinaryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecureUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CloudinaryFiles", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.CloudinaryFileIssue", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CloudinaryFileId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int>("CloudinaryFileIssueType")
                        .HasColumnType("integer");

                    b.HasKey("IssueId", "CloudinaryFileId");

                    b.HasIndex("CloudinaryFileId");

                    b.ToTable("CloudinaryFileIssues", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByEmail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<Guid?>("InitialPaymentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerifyByAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("IssueProcess")
                        .HasColumnType("integer");

                    b.Property<int>("IssueVisibility")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatingValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InitialPaymentId")
                        .IsUnique();

                    b.ToTable("Issues", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.IssueProcessingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<int>("IssueProcess")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueProcessingHistory", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.IssueRatingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedObject")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueRatingHistory", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.IssueVisibilityHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<int>("IssueVisibility")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueVisibilityHistory", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentValuePLN")
                        .HasColumnType("money");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Payments", "MRPayments");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.PaymentStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentStatusHistories", "MRPayments");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Payment_Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("Payment_Logs", "MRPayments");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Quarter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PrimarySignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("QuarterNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("QuarterResolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quarters", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.QuarterIssue", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("QuarterId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<bool?>("QuarterWinner")
                        .HasColumnType("boolean");

                    b.HasKey("IssueId", "QuarterId");

                    b.HasIndex("QuarterId");

                    b.ToTable("QuarterIssues", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.QuorumUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("QuorumUsers", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignaturePoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("SignaturePoolId");

                    b.ToTable("Signatures", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.SignaturePool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuarterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuarterId");

                    b.ToTable("SignaturePools", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Subscription", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Begin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ApplicationUserId");

                    b.ToTable("Subscriptions", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasColumnType("text")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.HasKey("SubscriptionId", "PaymentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("SubscriptionPayment");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Subscription_Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Subscription_Logs", "MRBasics");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.CloudinaryFileIssue", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.CloudinaryFile", "CloudinaryFile")
                        .WithMany("CloudinaryFileIssues")
                        .HasForeignKey("CloudinaryFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quorum.Domain.Entities.Issue", "Issue")
                        .WithMany("CloudinaryFileIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CloudinaryFile");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Issue", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Payment", "InitialPayment")
                        .WithOne("RelatedIssue")
                        .HasForeignKey("Quorum.Domain.Entities.Issue", "InitialPaymentId");

                    b.Navigation("InitialPayment");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.IssueProcessingHistory", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Issue", "Issue")
                        .WithMany("IssueProcessingHistories")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.IssueRatingHistory", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Issue", "Issue")
                        .WithMany("IssueRatingHistories")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.IssueVisibilityHistory", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Issue", "Issue")
                        .WithMany("IssueVisibilityHistories")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.PaymentStatusHistory", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Payment", "Payment")
                        .WithMany("PaymentStatusHistories")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Payment_Log", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Payment", "Payment")
                        .WithMany("Payment_Logs")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.QuarterIssue", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Issue", "Issue")
                        .WithMany("QuarterIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quorum.Domain.Entities.Quarter", "Quarter")
                        .WithMany("QuarterIssues")
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Signature", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Issue", "Issue")
                        .WithMany("Signatures")
                        .HasForeignKey("IssueId");

                    b.HasOne("Quorum.Domain.Entities.SignaturePool", "SignaturePool")
                        .WithMany("Signatures")
                        .HasForeignKey("SignaturePoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("SignaturePool");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.SignaturePool", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Quarter", "Quarter")
                        .WithMany()
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Payment", "Payment")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quorum.Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Subscription_Log", b =>
                {
                    b.HasOne("Quorum.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Subscription_Logs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.CloudinaryFile", b =>
                {
                    b.Navigation("CloudinaryFileIssues");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Issue", b =>
                {
                    b.Navigation("CloudinaryFileIssues");

                    b.Navigation("IssueProcessingHistories");

                    b.Navigation("IssueRatingHistories");

                    b.Navigation("IssueVisibilityHistories");

                    b.Navigation("QuarterIssues");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Payment", b =>
                {
                    b.Navigation("PaymentStatusHistories");

                    b.Navigation("Payment_Logs");

                    b.Navigation("RelatedIssue");

                    b.Navigation("SubscriptionPayments");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Quarter", b =>
                {
                    b.Navigation("QuarterIssues");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.SignaturePool", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("Quorum.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("SubscriptionPayments");

                    b.Navigation("Subscription_Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
