using PdfSharp.Pdf.IO;
using Quorum.Domain.Entities;
using Quorum.Domain.Enums;
using Quorum.Service.FilesManagement;
using Xunit;

namespace Quorum.Tests;

/// <summary>
/// Exercises the signature-sheet generator end to end: build an <see cref="Issue"/>, render it,
/// and parse the result back with a PDF reader.
/// <para>
/// These exist because of the gap ADR 0002 describes. The service had three members, one of
/// which (<c>WrtiePDFDocumentToFile</c>) called <c>Open</c> and <c>Add</c> before attaching a
/// writer — an invalid sequence that would have thrown on first use — and it survived three
/// years because nothing ever ran it. A test that asserts only "some bytes came back" would
/// have caught that; these go further and hand the bytes to a parser, because the failure mode
/// this migration risks is a file that is produced and is not a PDF.
/// </para>
/// <para>
/// The assertions are deliberately about structure rather than appearance. ADR 0002 records
/// that visual parity with the iTextSharp sheet is <i>not</i> a requirement — the old layout
/// has no signature area at all, so reproducing it would reproduce the defect. What must hold
/// is that generation runs, on this platform, and yields a document a reader accepts.
/// </para>
/// </summary>
public class IssuePdfGenerationTests
{
    static Issue AnIssue(string title = "A worked example initiative") => new()
    {
        Id = Guid.NewGuid(),
        Title = title,
        Question = "Should the council publish its procurement register monthly?",
        CreatedByEmail = "filed-as@example.test",
        IsVerifyByAdmin = true,
        RatingValue = 42.5m,
        IssueProcessingHistories = new List<IssueProcessingHistory>
        {
            new() { IssueProcess = IssueProcess.InCreation, CreatedAt = new DateTime(2026, 1, 2, 3, 4, 5, DateTimeKind.Utc) },
        },
    };

    [Fact]
    public void Generation_produces_a_document_a_pdf_reader_accepts()
    {
        var bytes = new IssuePDFService().GeneratePdfBytes(AnIssue());

        // A byte-length floor alone would pass on a truncated file, so parse it. TestPdfFile
        // returns the PDF version as an integer and 0 for anything it does not recognise.
        Assert.True(PdfReader.TestPdfFile(bytes) > 0, "the generated bytes are not a PDF");

        using var stream = new MemoryStream(bytes);
        using var document = PdfReader.Open(stream);

        Assert.Equal(1, document.PageCount);
    }

    [Fact]
    public void The_issues_title_reaches_the_document()
    {
        // The title is asserted through the document information dictionary rather than by
        // searching the page's content stream: the text on the page is written through an
        // embedded font's own encoding inside a compressed stream, so a byte search there
        // would be asserting an encoding rather than the title.
        var bytes = new IssuePDFService().GeneratePdfBytes(AnIssue("Monthly procurement register"));

        using var stream = new MemoryStream(bytes);
        using var document = PdfReader.Open(stream);

        Assert.Equal("Monthly procurement register", document.Info.Title);
    }

    [Fact]
    public void An_issue_whose_creator_has_been_removed_still_produces_a_sheet()
    {
        // The pre-migration code dereferenced a CreatedBy navigation with no null check, so an
        // issue filed by an account that no longer exists threw here instead of printing.
        var issue = AnIssue();
        issue.CreatedByEmail = null;

        var bytes = new IssuePDFService().GeneratePdfBytes(issue);

        Assert.True(PdfReader.TestPdfFile(bytes) > 0);
    }

    [Fact]
    public void An_issue_with_no_processing_history_still_produces_a_sheet()
    {
        var issue = AnIssue();
        issue.IssueProcessingHistories = null!;

        var bytes = new IssuePDFService().GeneratePdfBytes(issue);

        Assert.True(PdfReader.TestPdfFile(bytes) > 0);
    }

    [Fact]
    public void The_processing_history_reaches_the_page_and_not_only_the_metadata()
    {
        // Everything above could pass on a generator that wrote a correct but empty sheet, so
        // this asserts that the table's contents actually occupy the page: two hundred history
        // rows cannot fit on one A4 page at eleven point, whatever the exact row height.
        //
        // Comparing the bytes of two different issues would have been the cheaper guard and a
        // worthless one -- a PDF carries a creation timestamp, so any two renders differ and
        // the assertion could not fail.
        var issue = AnIssue();
        issue.IssueProcessingHistories = Enumerable.Range(0, 200)
            .Select(i => new IssueProcessingHistory
            {
                IssueProcess = IssueProcess.InCreation,
                CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddDays(i),
            })
            .ToList();

        var bytes = new IssuePDFService().GeneratePdfBytes(issue);

        using var stream = new MemoryStream(bytes);
        using var document = PdfReader.Open(stream);

        Assert.True(document.PageCount > 1, $"expected the history to spill onto more than one page, got {document.PageCount}");
    }

    [Fact]
    public void The_file_name_carries_the_title_with_path_separators_removed()
    {
        var name = new IssuePDFService().GetIssuePDFFileName(AnIssue("Roads / Bridges: phase 2"));

        Assert.EndsWith(".pdf", name);
        Assert.DoesNotContain("/", name);
        Assert.Contains("Bridges", name);
    }
}
