global using MR.Shared.DTOs.Signature;
global using MR.Shared.DTOs.Quarter;
global using MR.Shared.DTOs.Payment;
global using MR.Shared.DTOs.Issue;
global using MR.Shared.DTOs.SignaturePools;
global using System.Net;
global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using MR.Shared.DTOs.Issue.Public;